language: generic
cache:
  - ./images/fullnode/parity/.cache

services:
  - docker

script:
  # chains
  - ./images/build-fullnode-btcd.sh
  - ./images/fullnode/build-parity.sh

  # markets
  #cyber-markets images are assembled in CircleCI
  #- ./images/build-markets.sh
  - ./images/build-markets-app.sh

after_script:
  # sanity tests
  - ./images/run-fullnode-btcd.sh --version

